create table if not exists public.inquiry_logs (
  id bigint generated by default as identity primary key,
  role text not null,
  method text not null,
  language text,
  page text,
  user_agent text,
  referrer text,
  client_ip text,
  created_at timestamptz not null default now()
);

alter table public.inquiry_logs enable row level security;

revoke all on public.inquiry_logs from anon;
revoke all on public.inquiry_logs from authenticated;

create policy "service role only"
on public.inquiry_logs
as permissive
for all
to public
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');